name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ main ]

jobs:         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8
      
      # - name: Test credentials
        # run: |
            # echo "SECRET_KEY_1=${{ secrets.PLATFORMPASSWORD }}" > secrets.txt
            # echo "SECRET_KEY_2=${{ secrets.PLATFORMUSERNAME }}" >> secrets.txt
     
      # - name: Upload secrets file
        # uses: actions/upload-artifact@v4
        # with:
            # name: secrets-file
            # path: secrets.txt
  
      - name: Publish to Exchange
        run: |
          mvn clean deploy --settings .maven/settings.xml -DskipMunitTests -Dusername="${{ secrets.PLATFORMUSERNAME }}" -Dpassword="${{ secrets.PLATFORMPASSWORD }}"
    
      - name: Deploy to CloudHub 2.0
        run: |
          mvn clean deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy -Dusername="${{ secrets.PLATFORMUSERNAME }}" -Dpassword="${{ secrets.PLATFORMPASSWORD }}"